-- ConfigProfiles.lua
-- Example configuration profiles for different game scenarios

return {
	-- Hotline Miami inspired tight responsive camera
	HotlineMiami = {
		Pitch = 75,
		BaseHeight = 18,
		BaseDistance = 12,
		RotationMode = "WorldAligned",
		RotationYaw = 0,
		FollowSmoothTime = 0.08,
		AimSmoothTime = 0.12,
		ZoomSmoothTime = 0.2,
		AimWeight = 1.2,
		MovementWeight = 0.3,
		AimDominanceThreshold = 0.6,
		MaxLookAheadDistance = 10,
		MaxScreenOffset = 5,
		DeadzoneRadius = 1.0,
		DeadzoneResponse = 2.5,
		BaseZoom = 22,
		DynamicZoomEnabled = true,
		ZoomSpeedFactor = 0.25,
		MinZoom = 18,
		MaxZoom = 28,
		CollisionEnabled = true,
		CollisionPullback = 0.3,
		CeilingClearance = 1.5,
		MovementDirectionMode = "Hybrid",
	},

	-- Indoor focused tight quarters
	IndoorTactical = {
		Pitch = 70,
		BaseHeight = 15,
		BaseDistance = 10,
		RotationMode = "AimAligned",
		MaxYawAdjustment = 20,
		YawSmoothTime = 0.2,
		FollowSmoothTime = 0.1,
		AimSmoothTime = 0.15,
		BaseZoom = 18,
		DynamicZoomEnabled = false,
		CeilingClearance = 1.2,
		CollisionPullback = 0.2,
	},

	-- Outdoor large battlefield
	OutdoorBattlefield = {
		Pitch = 65,
		BaseHeight = 30,
		BaseDistance = 20,
		RotationMode = "WorldAligned",
		FollowSmoothTime = 0.2,
		AimSmoothTime = 0.25,
		MaxLookAheadDistance = 15,
		BaseZoom = 35,
		DynamicZoomEnabled = true,
		ZoomSpeedFactor = 0.4,
		MinZoom = 25,
		MaxZoom = 50,
	},

	-- Cinematic smooth camera for trailers
	Cinematic = {
		Pitch = 68,
		BaseHeight = 25,
		BaseDistance = 18,
		RotationMode = "MovementAligned",
		MaxYawAdjustment = 30,
		YawSmoothTime = 0.5,
		FollowSmoothTime = 0.35,
		AimSmoothTime = 0.4,
		ZoomSmoothTime = 0.6,
		DeadzoneRadius = 2.5,
		DeadzoneResponse = 1.5,
		DynamicZoomEnabled = true,
		ZoomSpeedFactor = 0.35,
	},

	-- Hyper responsive esports style
	Competitive = {
		Pitch = 72,
		BaseHeight = 20,
		BaseDistance = 14,
		RotationMode = "AimAligned",
		MaxYawAdjustment = 25,
		YawSmoothTime = 0.08,
		FollowSmoothTime = 0.05,
		AimSmoothTime = 0.08,
		ZoomSmoothTime = 0.12,
		AimWeight = 1.5,
		MovementWeight = 0.2,
		AimDominanceThreshold = 0.5,
		MaxLookAheadDistance = 12,
		DeadzoneRadius = 0.8,
		DeadzoneResponse = 3.0,
		BaseZoom = 24,
		DynamicZoomEnabled = true,
		ZoomSpeedFactor = 0.3,
		CollisionPullback = 0.2,
	},

	-- Stealth game slow camera
	Stealth = {
		Pitch = 73,
		BaseHeight = 16,
		BaseDistance = 11,
		RotationMode = "MovementAligned",
		MaxYawAdjustment = 15,
		YawSmoothTime = 0.4,
		FollowSmoothTime = 0.25,
		AimSmoothTime = 0.3,
		AimWeight = 0.8,
		MovementWeight = 0.6,
		MaxLookAheadDistance = 6,
		DeadzoneRadius = 2.0,
		BaseZoom = 20,
		DynamicZoomEnabled = false,
		CeilingClearance = 1.8,
	},

	-- Multi-floor dungeon crawler
	DungeonCrawler = {
		Pitch = 68,
		BaseHeight = 18,
		BaseDistance = 13,
		RotationMode = "WorldAligned",
		FollowSmoothTime = 0.12,
		AimSmoothTime = 0.18,
		MaxLookAheadDistance = 7,
		BaseZoom = 21,
		DynamicZoomEnabled = false,
		CollisionEnabled = true,
		CollisionPullback = 0.4,
		CeilingClearance = 1.6,
		ReferencePlaneMode = "SurfaceDetect",
		MovementDirectionMode = "Hybrid",
	},
}
